# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Burroughs Visualization
email: rejohnson@ucsd.edu
description: > # this means to ignore newlines until "baseurl:"
  This is a site to test different ideas regarding our Burroughs project,
  specifically working with visualization via D3.js, and trying to make it
  backend-less through Grunt, Jekyll, and GitHub Pages.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://remerjohnson.github.io/burroughs-visualization" # the base hostname & protocol for your site
twitter_username: ejones82
github_username:  remerjohnson

# Build settings
markdown: kramdown
